# CMake generated Testfile for 
# Source directory: /home/doyouseeme/volesti/test
# Build directory: /home/doyouseeme/volesti/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test_psrf "/home/doyouseeme/volesti/test/mcmc_diagnostics_test" "-tc=psrf")
set_tests_properties(test_psrf PROPERTIES  _BACKTRACE_TRIPLES "/home/doyouseeme/volesti/test/CMakeLists.txt;196;add_test;/home/doyouseeme/volesti/test/CMakeLists.txt;0;")
add_test(test_univariate_psrf "/home/doyouseeme/volesti/test/mcmc_diagnostics_test" "-tc=univariate_psrf")
set_tests_properties(test_univariate_psrf PROPERTIES  _BACKTRACE_TRIPLES "/home/doyouseeme/volesti/test/CMakeLists.txt;197;add_test;/home/doyouseeme/volesti/test/CMakeLists.txt;0;")
add_test(test_interval_psrf "/home/doyouseeme/volesti/test/mcmc_diagnostics_test" "-tc=interval_psrf")
set_tests_properties(test_interval_psrf PROPERTIES  _BACKTRACE_TRIPLES "/home/doyouseeme/volesti/test/CMakeLists.txt;198;add_test;/home/doyouseeme/volesti/test/CMakeLists.txt;0;")
add_test(test_ess "/home/doyouseeme/volesti/test/mcmc_diagnostics_test" "-tc=ess")
set_tests_properties(test_ess PROPERTIES  _BACKTRACE_TRIPLES "/home/doyouseeme/volesti/test/CMakeLists.txt;199;add_test;/home/doyouseeme/volesti/test/CMakeLists.txt;0;")
add_test(test_geweke "/home/doyouseeme/volesti/test/mcmc_diagnostics_test" "-tc=geweke")
set_tests_properties(test_geweke PROPERTIES  _BACKTRACE_TRIPLES "/home/doyouseeme/volesti/test/CMakeLists.txt;200;add_test;/home/doyouseeme/volesti/test/CMakeLists.txt;0;")
add_test(test_raftery "/home/doyouseeme/volesti/test/mcmc_diagnostics_test" "-tc=raftery")
set_tests_properties(test_raftery PROPERTIES  _BACKTRACE_TRIPLES "/home/doyouseeme/volesti/test/CMakeLists.txt;201;add_test;/home/doyouseeme/volesti/test/CMakeLists.txt;0;")
add_test(test_dikin "/home/doyouseeme/volesti/test/sampling_test" "-tc=dikin")
set_tests_properties(test_dikin PROPERTIES  _BACKTRACE_TRIPLES "/home/doyouseeme/volesti/test/CMakeLists.txt;204;add_test;/home/doyouseeme/volesti/test/CMakeLists.txt;0;")
add_test(test_john "/home/doyouseeme/volesti/test/sampling_test" "-tc=john")
set_tests_properties(test_john PROPERTIES  _BACKTRACE_TRIPLES "/home/doyouseeme/volesti/test/CMakeLists.txt;205;add_test;/home/doyouseeme/volesti/test/CMakeLists.txt;0;")
add_test(test_vaidya "/home/doyouseeme/volesti/test/sampling_test" "-tc=vaidya")
set_tests_properties(test_vaidya PROPERTIES  _BACKTRACE_TRIPLES "/home/doyouseeme/volesti/test/CMakeLists.txt;206;add_test;/home/doyouseeme/volesti/test/CMakeLists.txt;0;")
add_test(test_brdhr "/home/doyouseeme/volesti/test/sampling_test" "-tc=brdhr")
set_tests_properties(test_brdhr PROPERTIES  _BACKTRACE_TRIPLES "/home/doyouseeme/volesti/test/CMakeLists.txt;207;add_test;/home/doyouseeme/volesti/test/CMakeLists.txt;0;")
add_test(test_bcdhr "/home/doyouseeme/volesti/test/sampling_test" "-tc=bcdhr")
set_tests_properties(test_bcdhr PROPERTIES  _BACKTRACE_TRIPLES "/home/doyouseeme/volesti/test/CMakeLists.txt;208;add_test;/home/doyouseeme/volesti/test/CMakeLists.txt;0;")
add_test(test_grdhr "/home/doyouseeme/volesti/test/sampling_test" "-tc=grdhr")
set_tests_properties(test_grdhr PROPERTIES  _BACKTRACE_TRIPLES "/home/doyouseeme/volesti/test/CMakeLists.txt;209;add_test;/home/doyouseeme/volesti/test/CMakeLists.txt;0;")
add_test(test_gbaw "/home/doyouseeme/volesti/test/sampling_test" "-tc=gbaw")
set_tests_properties(test_gbaw PROPERTIES  _BACKTRACE_TRIPLES "/home/doyouseeme/volesti/test/CMakeLists.txt;210;add_test;/home/doyouseeme/volesti/test/CMakeLists.txt;0;")
add_test(test_ghmc "/home/doyouseeme/volesti/test/sampling_test" "-tc=ghmc")
set_tests_properties(test_ghmc PROPERTIES  _BACKTRACE_TRIPLES "/home/doyouseeme/volesti/test/CMakeLists.txt;211;add_test;/home/doyouseeme/volesti/test/CMakeLists.txt;0;")
add_test(test_mmcs "/home/doyouseeme/volesti/test/mmcs_test" "-tc=mmcs")
set_tests_properties(test_mmcs PROPERTIES  _BACKTRACE_TRIPLES "/home/doyouseeme/volesti/test/CMakeLists.txt;214;add_test;/home/doyouseeme/volesti/test/CMakeLists.txt;0;")
add_test(ode_solvers_test_first_order "/home/doyouseeme/volesti/test/ode_solvers_test" "-tc=first_order")
set_tests_properties(ode_solvers_test_first_order PROPERTIES  _BACKTRACE_TRIPLES "/home/doyouseeme/volesti/test/CMakeLists.txt;217;add_test;/home/doyouseeme/volesti/test/CMakeLists.txt;0;")
add_test(ode_solvers_test_second_order "/home/doyouseeme/volesti/test/ode_solvers_test" "-tc=second_order")
set_tests_properties(ode_solvers_test_second_order PROPERTIES  _BACKTRACE_TRIPLES "/home/doyouseeme/volesti/test/CMakeLists.txt;219;add_test;/home/doyouseeme/volesti/test/CMakeLists.txt;0;")
add_test(root_finders_test_root_finders "/home/doyouseeme/volesti/test/root_finders_test" "-tc=root_finders")
set_tests_properties(root_finders_test_root_finders PROPERTIES  _BACKTRACE_TRIPLES "/home/doyouseeme/volesti/test/CMakeLists.txt;223;add_test;/home/doyouseeme/volesti/test/CMakeLists.txt;0;")
add_test(crhmc_polytope_test_preparation "/home/doyouseeme/volesti/test/crhmc_polytope_preparation_test" "-tc=test_preparation_crhmc")
set_tests_properties(crhmc_polytope_test_preparation PROPERTIES  _BACKTRACE_TRIPLES "/home/doyouseeme/volesti/test/CMakeLists.txt;230;add_test;/home/doyouseeme/volesti/test/CMakeLists.txt;0;")
add_test(crhmc_test_fixed_vars "/home/doyouseeme/volesti/test/crhmc_polytope_preparation_test" "-tc=test_fixed_vars_crhmc")
set_tests_properties(crhmc_test_fixed_vars PROPERTIES  _BACKTRACE_TRIPLES "/home/doyouseeme/volesti/test/CMakeLists.txt;232;add_test;/home/doyouseeme/volesti/test/CMakeLists.txt;0;")
add_test(crhmc_test_dep_vars "/home/doyouseeme/volesti/test/crhmc_polytope_preparation_test" "-tc=test_dep_vars_crhmc")
set_tests_properties(crhmc_test_dep_vars PROPERTIES  _BACKTRACE_TRIPLES "/home/doyouseeme/volesti/test/CMakeLists.txt;234;add_test;/home/doyouseeme/volesti/test/CMakeLists.txt;0;")
add_test(crhmc_test_center_computation "/home/doyouseeme/volesti/test/crhmc_polytope_preparation_test" "-tc=test_center_computation")
set_tests_properties(crhmc_test_center_computation PROPERTIES  _BACKTRACE_TRIPLES "/home/doyouseeme/volesti/test/CMakeLists.txt;236;add_test;/home/doyouseeme/volesti/test/CMakeLists.txt;0;")
add_test(boundary_oracles_test_h_poly_oracles "/home/doyouseeme/volesti/test/boundary_oracles_test" "-tc=h_poly_oracles")
set_tests_properties(boundary_oracles_test_h_poly_oracles PROPERTIES  _BACKTRACE_TRIPLES "/home/doyouseeme/volesti/test/CMakeLists.txt;240;add_test;/home/doyouseeme/volesti/test/CMakeLists.txt;0;")
add_test(volume_sob_hpolytope_cube "/home/doyouseeme/volesti/test/volume_sob_hpolytope" "-tc=cube")
set_tests_properties(volume_sob_hpolytope_cube PROPERTIES  _BACKTRACE_TRIPLES "/home/doyouseeme/volesti/test/CMakeLists.txt;244;add_test;/home/doyouseeme/volesti/test/CMakeLists.txt;0;")
add_test(volume_sob_hpolytope_cross "/home/doyouseeme/volesti/test/volume_sob_hpolytope" "-tc=cross")
set_tests_properties(volume_sob_hpolytope_cross PROPERTIES  _BACKTRACE_TRIPLES "/home/doyouseeme/volesti/test/CMakeLists.txt;245;add_test;/home/doyouseeme/volesti/test/CMakeLists.txt;0;")
add_test(volume_sob_hpolytope_birkhoff "/home/doyouseeme/volesti/test/volume_sob_hpolytope" "-tc=birk")
set_tests_properties(volume_sob_hpolytope_birkhoff PROPERTIES  _BACKTRACE_TRIPLES "/home/doyouseeme/volesti/test/CMakeLists.txt;246;add_test;/home/doyouseeme/volesti/test/CMakeLists.txt;0;")
add_test(volume_sob_hpolytope_prod_simplex "/home/doyouseeme/volesti/test/volume_sob_hpolytope" "-tc=prod_simplex")
set_tests_properties(volume_sob_hpolytope_prod_simplex PROPERTIES  _BACKTRACE_TRIPLES "/home/doyouseeme/volesti/test/CMakeLists.txt;247;add_test;/home/doyouseeme/volesti/test/CMakeLists.txt;0;")
add_test(volume_sob_hpolytope_simplex "/home/doyouseeme/volesti/test/volume_sob_hpolytope" "-tc=simplex")
set_tests_properties(volume_sob_hpolytope_simplex PROPERTIES  _BACKTRACE_TRIPLES "/home/doyouseeme/volesti/test/CMakeLists.txt;248;add_test;/home/doyouseeme/volesti/test/CMakeLists.txt;0;")
add_test(volume_sob_hpolytope_skinny_cube "/home/doyouseeme/volesti/test/volume_sob_hpolytope" "-tc=skinny_cube")
set_tests_properties(volume_sob_hpolytope_skinny_cube PROPERTIES  _BACKTRACE_TRIPLES "/home/doyouseeme/volesti/test/CMakeLists.txt;249;add_test;/home/doyouseeme/volesti/test/CMakeLists.txt;0;")
add_test(volume_sob_hpolytope_cube_overflow "/home/doyouseeme/volesti/test/volume_sob_hpolytope" "-tc=cube_overflow")
set_tests_properties(volume_sob_hpolytope_cube_overflow PROPERTIES  TIMEOUT "1" _BACKTRACE_TRIPLES "/home/doyouseeme/volesti/test/CMakeLists.txt;250;add_test;/home/doyouseeme/volesti/test/CMakeLists.txt;0;")
add_test(volume_sob_vpolytope_cube "/home/doyouseeme/volesti/test/volume_sob_vpolytope" "-tc=cube")
set_tests_properties(volume_sob_vpolytope_cube PROPERTIES  _BACKTRACE_TRIPLES "/home/doyouseeme/volesti/test/CMakeLists.txt;254;add_test;/home/doyouseeme/volesti/test/CMakeLists.txt;0;")
add_test(volume_sob_vpolytope_cross "/home/doyouseeme/volesti/test/volume_sob_vpolytope" "-tc=cross")
set_tests_properties(volume_sob_vpolytope_cross PROPERTIES  _BACKTRACE_TRIPLES "/home/doyouseeme/volesti/test/CMakeLists.txt;255;add_test;/home/doyouseeme/volesti/test/CMakeLists.txt;0;")
add_test(volume_sob_vpolytope_simplex "/home/doyouseeme/volesti/test/volume_sob_vpolytope" "-tc=simplex")
set_tests_properties(volume_sob_vpolytope_simplex PROPERTIES  _BACKTRACE_TRIPLES "/home/doyouseeme/volesti/test/CMakeLists.txt;256;add_test;/home/doyouseeme/volesti/test/CMakeLists.txt;0;")
add_test(volume_cg_hpolytope_cube "/home/doyouseeme/volesti/test/volume_cg_hpolytope" "-tc=cube")
set_tests_properties(volume_cg_hpolytope_cube PROPERTIES  _BACKTRACE_TRIPLES "/home/doyouseeme/volesti/test/CMakeLists.txt;259;add_test;/home/doyouseeme/volesti/test/CMakeLists.txt;0;")
add_test(volume_cg_hpolytope_cross "/home/doyouseeme/volesti/test/volume_cg_hpolytope" "-tc=cross")
set_tests_properties(volume_cg_hpolytope_cross PROPERTIES  _BACKTRACE_TRIPLES "/home/doyouseeme/volesti/test/CMakeLists.txt;260;add_test;/home/doyouseeme/volesti/test/CMakeLists.txt;0;")
add_test(volume_cg_hpolytope_birkhoff "/home/doyouseeme/volesti/test/volume_cg_hpolytope" "-tc=birk")
set_tests_properties(volume_cg_hpolytope_birkhoff PROPERTIES  _BACKTRACE_TRIPLES "/home/doyouseeme/volesti/test/CMakeLists.txt;261;add_test;/home/doyouseeme/volesti/test/CMakeLists.txt;0;")
add_test(volume_cg_hpolytope_prod_simplex "/home/doyouseeme/volesti/test/volume_cg_hpolytope" "-tc=prod_simplex")
set_tests_properties(volume_cg_hpolytope_prod_simplex PROPERTIES  _BACKTRACE_TRIPLES "/home/doyouseeme/volesti/test/CMakeLists.txt;262;add_test;/home/doyouseeme/volesti/test/CMakeLists.txt;0;")
add_test(volume_cg_hpolytope_simplex "/home/doyouseeme/volesti/test/volume_cg_hpolytope" "-tc=simplex")
set_tests_properties(volume_cg_hpolytope_simplex PROPERTIES  _BACKTRACE_TRIPLES "/home/doyouseeme/volesti/test/CMakeLists.txt;263;add_test;/home/doyouseeme/volesti/test/CMakeLists.txt;0;")
add_test(volume_cg_hpolytope_skinny_cube "/home/doyouseeme/volesti/test/volume_cg_hpolytope" "-tc=skinny_cube")
set_tests_properties(volume_cg_hpolytope_skinny_cube PROPERTIES  _BACKTRACE_TRIPLES "/home/doyouseeme/volesti/test/CMakeLists.txt;264;add_test;/home/doyouseeme/volesti/test/CMakeLists.txt;0;")
add_test(volume_cg_vpolytope_cube "/home/doyouseeme/volesti/test/volume_cg_vpolytope" "-tc=cube")
set_tests_properties(volume_cg_vpolytope_cube PROPERTIES  _BACKTRACE_TRIPLES "/home/doyouseeme/volesti/test/CMakeLists.txt;267;add_test;/home/doyouseeme/volesti/test/CMakeLists.txt;0;")
add_test(volume_cg_vpolytope_cross "/home/doyouseeme/volesti/test/volume_cg_vpolytope" "-tc=cross")
set_tests_properties(volume_cg_vpolytope_cross PROPERTIES  _BACKTRACE_TRIPLES "/home/doyouseeme/volesti/test/CMakeLists.txt;268;add_test;/home/doyouseeme/volesti/test/CMakeLists.txt;0;")
add_test(volume_cg_vpolytope_simplex "/home/doyouseeme/volesti/test/volume_cg_vpolytope" "-tc=simplex")
set_tests_properties(volume_cg_vpolytope_simplex PROPERTIES  _BACKTRACE_TRIPLES "/home/doyouseeme/volesti/test/CMakeLists.txt;269;add_test;/home/doyouseeme/volesti/test/CMakeLists.txt;0;")
add_test(volume_cb_hpolytope_cube "/home/doyouseeme/volesti/test/volume_cb_hpolytope" "-tc=cube")
set_tests_properties(volume_cb_hpolytope_cube PROPERTIES  _BACKTRACE_TRIPLES "/home/doyouseeme/volesti/test/CMakeLists.txt;272;add_test;/home/doyouseeme/volesti/test/CMakeLists.txt;0;")
add_test(volume_cb_hpolytope_cross "/home/doyouseeme/volesti/test/volume_cb_hpolytope" "-tc=cross")
set_tests_properties(volume_cb_hpolytope_cross PROPERTIES  _BACKTRACE_TRIPLES "/home/doyouseeme/volesti/test/CMakeLists.txt;273;add_test;/home/doyouseeme/volesti/test/CMakeLists.txt;0;")
add_test(volume_cb_hpolytope_birkhoff "/home/doyouseeme/volesti/test/volume_cb_hpolytope" "-tc=birk")
set_tests_properties(volume_cb_hpolytope_birkhoff PROPERTIES  _BACKTRACE_TRIPLES "/home/doyouseeme/volesti/test/CMakeLists.txt;274;add_test;/home/doyouseeme/volesti/test/CMakeLists.txt;0;")
add_test(volume_cb_hpolytope_prod_simplex "/home/doyouseeme/volesti/test/volume_cb_hpolytope" "-tc=prod_simplex")
set_tests_properties(volume_cb_hpolytope_prod_simplex PROPERTIES  _BACKTRACE_TRIPLES "/home/doyouseeme/volesti/test/CMakeLists.txt;275;add_test;/home/doyouseeme/volesti/test/CMakeLists.txt;0;")
add_test(volume_cb_hpolytope_simplex "/home/doyouseeme/volesti/test/volume_cb_hpolytope" "-tc=simplex")
set_tests_properties(volume_cb_hpolytope_simplex PROPERTIES  _BACKTRACE_TRIPLES "/home/doyouseeme/volesti/test/CMakeLists.txt;276;add_test;/home/doyouseeme/volesti/test/CMakeLists.txt;0;")
add_test(volume_cb_hpolytope_skinny_cube "/home/doyouseeme/volesti/test/volume_cb_hpolytope" "-tc=skinny_cube")
set_tests_properties(volume_cb_hpolytope_skinny_cube PROPERTIES  _BACKTRACE_TRIPLES "/home/doyouseeme/volesti/test/CMakeLists.txt;277;add_test;/home/doyouseeme/volesti/test/CMakeLists.txt;0;")
add_test(volume_cb_vpolytope_cube "/home/doyouseeme/volesti/test/volume_cb_vpolytope" "-tc=cube")
set_tests_properties(volume_cb_vpolytope_cube PROPERTIES  _BACKTRACE_TRIPLES "/home/doyouseeme/volesti/test/CMakeLists.txt;280;add_test;/home/doyouseeme/volesti/test/CMakeLists.txt;0;")
add_test(volume_cb_vpolytope_cross "/home/doyouseeme/volesti/test/volume_cb_vpolytope" "-tc=cross")
set_tests_properties(volume_cb_vpolytope_cross PROPERTIES  _BACKTRACE_TRIPLES "/home/doyouseeme/volesti/test/CMakeLists.txt;281;add_test;/home/doyouseeme/volesti/test/CMakeLists.txt;0;")
add_test(volume_cb_vpolytope_simplex "/home/doyouseeme/volesti/test/volume_cb_vpolytope" "-tc=simplex")
set_tests_properties(volume_cb_vpolytope_simplex PROPERTIES  _BACKTRACE_TRIPLES "/home/doyouseeme/volesti/test/CMakeLists.txt;282;add_test;/home/doyouseeme/volesti/test/CMakeLists.txt;0;")
add_test(volume_cb_zonotopes_uniform_zonotopes "/home/doyouseeme/volesti/test/volume_cb_zonotopes" "-tc=uniform_zonotopes")
set_tests_properties(volume_cb_zonotopes_uniform_zonotopes PROPERTIES  _BACKTRACE_TRIPLES "/home/doyouseeme/volesti/test/CMakeLists.txt;285;add_test;/home/doyouseeme/volesti/test/CMakeLists.txt;0;")
add_test(volume_cb_vpoly_intersection_vpoly_random_vpoly_sphere "/home/doyouseeme/volesti/test/volume_cb_vpoly_intersection_vpoly" "-tc=random_vpoly_sphere")
set_tests_properties(volume_cb_vpoly_intersection_vpoly_random_vpoly_sphere PROPERTIES  _BACKTRACE_TRIPLES "/home/doyouseeme/volesti/test/CMakeLists.txt;289;add_test;/home/doyouseeme/volesti/test/CMakeLists.txt;0;")
add_test(test_round_min_ellipsoid "/home/doyouseeme/volesti/test/new_rounding_test" "-tc=round_min_ellipsoid")
set_tests_properties(test_round_min_ellipsoid PROPERTIES  _BACKTRACE_TRIPLES "/home/doyouseeme/volesti/test/CMakeLists.txt;293;add_test;/home/doyouseeme/volesti/test/CMakeLists.txt;0;")
add_test(test_round_max_ellipsoid "/home/doyouseeme/volesti/test/new_rounding_test" "-tc=round_max_ellipsoid")
set_tests_properties(test_round_max_ellipsoid PROPERTIES  _BACKTRACE_TRIPLES "/home/doyouseeme/volesti/test/CMakeLists.txt;295;add_test;/home/doyouseeme/volesti/test/CMakeLists.txt;0;")
add_test(test_round_svd "/home/doyouseeme/volesti/test/new_rounding_test" "-tc=round_svd")
set_tests_properties(test_round_svd PROPERTIES  _BACKTRACE_TRIPLES "/home/doyouseeme/volesti/test/CMakeLists.txt;297;add_test;/home/doyouseeme/volesti/test/CMakeLists.txt;0;")
add_test(logconcave_sampling_test_hmc "/home/doyouseeme/volesti/test/logconcave_sampling_test" "-tc=hmc")
set_tests_properties(logconcave_sampling_test_hmc PROPERTIES  _BACKTRACE_TRIPLES "/home/doyouseeme/volesti/test/CMakeLists.txt;301;add_test;/home/doyouseeme/volesti/test/CMakeLists.txt;0;")
add_test(logconcave_sampling_test_uld "/home/doyouseeme/volesti/test/logconcave_sampling_test" "-tc=uld")
set_tests_properties(logconcave_sampling_test_uld PROPERTIES  _BACKTRACE_TRIPLES "/home/doyouseeme/volesti/test/CMakeLists.txt;303;add_test;/home/doyouseeme/volesti/test/CMakeLists.txt;0;")
add_test(logconcave_sampling_test_exponential_biomass_sampling "/home/doyouseeme/volesti/test/logconcave_sampling_test" "-tc=exponential_biomass_sampling")
set_tests_properties(logconcave_sampling_test_exponential_biomass_sampling PROPERTIES  _BACKTRACE_TRIPLES "/home/doyouseeme/volesti/test/CMakeLists.txt;305;add_test;/home/doyouseeme/volesti/test/CMakeLists.txt;0;")
add_test(logconcave_sampling_test_nuts_hmc_truncated "/home/doyouseeme/volesti/test/logconcave_sampling_test" "-tc=benchmark_nuts_hmc_truncated")
set_tests_properties(logconcave_sampling_test_nuts_hmc_truncated PROPERTIES  _BACKTRACE_TRIPLES "/home/doyouseeme/volesti/test/CMakeLists.txt;307;add_test;/home/doyouseeme/volesti/test/CMakeLists.txt;0;")
add_test(logconcave_sampling_test_nuts_hmc "/home/doyouseeme/volesti/test/logconcave_sampling_test" "-tc=benchmark_nuts_hmc")
set_tests_properties(logconcave_sampling_test_nuts_hmc PROPERTIES  _BACKTRACE_TRIPLES "/home/doyouseeme/volesti/test/CMakeLists.txt;309;add_test;/home/doyouseeme/volesti/test/CMakeLists.txt;0;")
add_test(crhmc_sampling_test_crhmc "/home/doyouseeme/volesti/test/crhmc_sampling_test" "-tc=crhmc")
set_tests_properties(crhmc_sampling_test_crhmc PROPERTIES  _BACKTRACE_TRIPLES "/home/doyouseeme/volesti/test/CMakeLists.txt;315;add_test;/home/doyouseeme/volesti/test/CMakeLists.txt;0;")
add_test(crhmc_test_polytope_sampling "/home/doyouseeme/volesti/test/crhmc_sampling_test" "-tc=test_polytope_sampling_crhmc")
set_tests_properties(crhmc_test_polytope_sampling PROPERTIES  _BACKTRACE_TRIPLES "/home/doyouseeme/volesti/test/CMakeLists.txt;317;add_test;/home/doyouseeme/volesti/test/CMakeLists.txt;0;")
add_test(crhmc_test_sparse_sampling "/home/doyouseeme/volesti/test/crhmc_sampling_test" "-tc=test_sampling_sparse_problem")
set_tests_properties(crhmc_test_sparse_sampling PROPERTIES  _BACKTRACE_TRIPLES "/home/doyouseeme/volesti/test/CMakeLists.txt;319;add_test;/home/doyouseeme/volesti/test/CMakeLists.txt;0;")
add_test(simple_mc_integration_over_limits "/home/doyouseeme/volesti/test/simple_mc_integration" "-tc=rectangle")
set_tests_properties(simple_mc_integration_over_limits PROPERTIES  _BACKTRACE_TRIPLES "/home/doyouseeme/volesti/test/CMakeLists.txt;322;add_test;/home/doyouseeme/volesti/test/CMakeLists.txt;0;")
add_test(simple_mc_integration_over_cubes "/home/doyouseeme/volesti/test/simple_mc_integration" "-tc=cube")
set_tests_properties(simple_mc_integration_over_cubes PROPERTIES  _BACKTRACE_TRIPLES "/home/doyouseeme/volesti/test/CMakeLists.txt;324;add_test;/home/doyouseeme/volesti/test/CMakeLists.txt;0;")
add_test(simple_mc_integration_over_simplices "/home/doyouseeme/volesti/test/simple_mc_integration" "-tc=simplex")
set_tests_properties(simple_mc_integration_over_simplices PROPERTIES  _BACKTRACE_TRIPLES "/home/doyouseeme/volesti/test/CMakeLists.txt;326;add_test;/home/doyouseeme/volesti/test/CMakeLists.txt;0;")
add_test(simple_mc_integration_over_product_simplices "/home/doyouseeme/volesti/test/simple_mc_integration" "-tc=prod_simplex")
set_tests_properties(simple_mc_integration_over_product_simplices PROPERTIES  _BACKTRACE_TRIPLES "/home/doyouseeme/volesti/test/CMakeLists.txt;328;add_test;/home/doyouseeme/volesti/test/CMakeLists.txt;0;")
add_test(simple_mc_integration_over_cross_polytopes "/home/doyouseeme/volesti/test/simple_mc_integration" "-tc=cross")
set_tests_properties(simple_mc_integration_over_cross_polytopes PROPERTIES  _BACKTRACE_TRIPLES "/home/doyouseeme/volesti/test/CMakeLists.txt;330;add_test;/home/doyouseeme/volesti/test/CMakeLists.txt;0;")
add_test(simple_mc_integration_over_birkhoff_polytopes "/home/doyouseeme/volesti/test/simple_mc_integration" "-tc=birkhoff")
set_tests_properties(simple_mc_integration_over_birkhoff_polytopes PROPERTIES  _BACKTRACE_TRIPLES "/home/doyouseeme/volesti/test/CMakeLists.txt;332;add_test;/home/doyouseeme/volesti/test/CMakeLists.txt;0;")
add_test(order_polytope_basics "/home/doyouseeme/volesti/test/order_polytope" "-tc=basics")
set_tests_properties(order_polytope_basics PROPERTIES  _BACKTRACE_TRIPLES "/home/doyouseeme/volesti/test/CMakeLists.txt;336;add_test;/home/doyouseeme/volesti/test/CMakeLists.txt;0;")
add_test(order_polytope_line_intersect "/home/doyouseeme/volesti/test/order_polytope" "-tc=line_intersect")
set_tests_properties(order_polytope_line_intersect PROPERTIES  _BACKTRACE_TRIPLES "/home/doyouseeme/volesti/test/CMakeLists.txt;337;add_test;/home/doyouseeme/volesti/test/CMakeLists.txt;0;")
add_test(order_polytope_reflection "/home/doyouseeme/volesti/test/order_polytope" "-tc=reflection")
set_tests_properties(order_polytope_reflection PROPERTIES  _BACKTRACE_TRIPLES "/home/doyouseeme/volesti/test/CMakeLists.txt;338;add_test;/home/doyouseeme/volesti/test/CMakeLists.txt;0;")
add_test(order_polytope_vec_mult "/home/doyouseeme/volesti/test/order_polytope" "-tc=vec_mult")
set_tests_properties(order_polytope_vec_mult PROPERTIES  _BACKTRACE_TRIPLES "/home/doyouseeme/volesti/test/CMakeLists.txt;339;add_test;/home/doyouseeme/volesti/test/CMakeLists.txt;0;")
add_test(test_corre_spectra_classes "/home/doyouseeme/volesti/test/matrix_sampling_test" "-tc=corre_spectra")
set_tests_properties(test_corre_spectra_classes PROPERTIES  _BACKTRACE_TRIPLES "/home/doyouseeme/volesti/test/CMakeLists.txt;342;add_test;/home/doyouseeme/volesti/test/CMakeLists.txt;0;")
add_test(test_new_ball_uniform "/home/doyouseeme/volesti/test/matrix_sampling_test" "-tc=new_ball_uniform")
set_tests_properties(test_new_ball_uniform PROPERTIES  _BACKTRACE_TRIPLES "/home/doyouseeme/volesti/test/CMakeLists.txt;343;add_test;/home/doyouseeme/volesti/test/CMakeLists.txt;0;")
add_test(test_new_billiard_uniform "/home/doyouseeme/volesti/test/matrix_sampling_test" "-tc=new_billiard_uniform")
set_tests_properties(test_new_billiard_uniform PROPERTIES  _BACKTRACE_TRIPLES "/home/doyouseeme/volesti/test/CMakeLists.txt;344;add_test;/home/doyouseeme/volesti/test/CMakeLists.txt;0;")
add_test(test_new_accelerated_billiard_uniform "/home/doyouseeme/volesti/test/matrix_sampling_test" "-tc=new_accelerated_billiard_uniform")
set_tests_properties(test_new_accelerated_billiard_uniform PROPERTIES  _BACKTRACE_TRIPLES "/home/doyouseeme/volesti/test/CMakeLists.txt;345;add_test;/home/doyouseeme/volesti/test/CMakeLists.txt;0;")
add_test(test_new_ball_uniform_MT "/home/doyouseeme/volesti/test/matrix_sampling_test" "-tc=new_ball_uniform_MT")
set_tests_properties(test_new_ball_uniform_MT PROPERTIES  _BACKTRACE_TRIPLES "/home/doyouseeme/volesti/test/CMakeLists.txt;346;add_test;/home/doyouseeme/volesti/test/CMakeLists.txt;0;")
add_test(test_new_rdhr_uniform_MT "/home/doyouseeme/volesti/test/matrix_sampling_test" "-tc=new_rdhr_uniform_MT")
set_tests_properties(test_new_rdhr_uniform_MT PROPERTIES  _BACKTRACE_TRIPLES "/home/doyouseeme/volesti/test/CMakeLists.txt;347;add_test;/home/doyouseeme/volesti/test/CMakeLists.txt;0;")
add_test(test_new_billiard_uniform_MT "/home/doyouseeme/volesti/test/matrix_sampling_test" "-tc=new_billiard_uniform_MT")
set_tests_properties(test_new_billiard_uniform_MT PROPERTIES  _BACKTRACE_TRIPLES "/home/doyouseeme/volesti/test/CMakeLists.txt;348;add_test;/home/doyouseeme/volesti/test/CMakeLists.txt;0;")
add_test(test_new_accelerated_billiard_uniform_MT "/home/doyouseeme/volesti/test/matrix_sampling_test" "-tc=new_accelerated_billiard_uniform_MT")
set_tests_properties(test_new_accelerated_billiard_uniform_MT PROPERTIES  _BACKTRACE_TRIPLES "/home/doyouseeme/volesti/test/CMakeLists.txt;349;add_test;/home/doyouseeme/volesti/test/CMakeLists.txt;0;")
