// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// generator_sdp
void generator_sdp(Rcpp::Nullable<int> nn, Rcpp::Nullable<int> mm);
RcppExport SEXP _volesti_generator_sdp(SEXP nnSEXP, SEXP mmSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::Nullable<int> >::type nn(nnSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<int> >::type mm(mmSEXP);
    generator_sdp(nn, mm);
    return R_NilValue;
END_RCPP
}
// sample_points
Rcpp::NumericMatrix sample_points(Rcpp::Nullable<Rcpp::CharacterVector> file, Rcpp::Nullable<std::string> distribution, Rcpp::Nullable<unsigned int> N, Rcpp::Nullable<unsigned int> walk_length, Rcpp::Nullable<double> Temperature, Rcpp::Nullable<unsigned int> random_walk);
RcppExport SEXP _volesti_sample_points(SEXP fileSEXP, SEXP distributionSEXP, SEXP NSEXP, SEXP walk_lengthSEXP, SEXP TemperatureSEXP, SEXP random_walkSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::CharacterVector> >::type file(fileSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<std::string> >::type distribution(distributionSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<unsigned int> >::type N(NSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<unsigned int> >::type walk_length(walk_lengthSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type Temperature(TemperatureSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<unsigned int> >::type random_walk(random_walkSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_points(file, distribution, N, walk_length, Temperature, random_walk));
    return rcpp_result_gen;
END_RCPP
}
// sdp_approx
Rcpp::NumericVector sdp_approx(Rcpp::Nullable<Rcpp::CharacterVector> file, Rcpp::Nullable<int> N, Rcpp::Nullable<int> random_walk, Rcpp::Nullable<unsigned int> walk_length);
RcppExport SEXP _volesti_sdp_approx(SEXP fileSEXP, SEXP NSEXP, SEXP random_walkSEXP, SEXP walk_lengthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::CharacterVector> >::type file(fileSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<int> >::type N(NSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<int> >::type random_walk(random_walkSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<unsigned int> >::type walk_length(walk_lengthSEXP);
    rcpp_result_gen = Rcpp::wrap(sdp_approx(file, N, random_walk, walk_length));
    return rcpp_result_gen;
END_RCPP
}
// volume
Rcpp::NumericVector volume(Rcpp::Nullable<Rcpp::CharacterVector> file, Rcpp::Nullable<unsigned int> walk_step, Rcpp::Nullable<double> error, Rcpp::Nullable<Rcpp::NumericVector> InnerBall, Rcpp::Nullable<std::string> Algo, Rcpp::Nullable<std::string> WalkType, Rcpp::Nullable<bool> rounding, Rcpp::Nullable<Rcpp::List> Parameters);
RcppExport SEXP _volesti_volume(SEXP fileSEXP, SEXP walk_stepSEXP, SEXP errorSEXP, SEXP InnerBallSEXP, SEXP AlgoSEXP, SEXP WalkTypeSEXP, SEXP roundingSEXP, SEXP ParametersSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::CharacterVector> >::type file(fileSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<unsigned int> >::type walk_step(walk_stepSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type error(errorSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type InnerBall(InnerBallSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<std::string> >::type Algo(AlgoSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<std::string> >::type WalkType(WalkTypeSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<bool> >::type rounding(roundingSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::List> >::type Parameters(ParametersSEXP);
    rcpp_result_gen = Rcpp::wrap(volume(file, walk_step, error, InnerBall, Algo, WalkType, rounding, Parameters));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_volesti_generator_sdp", (DL_FUNC) &_volesti_generator_sdp, 2},
    {"_volesti_sample_points", (DL_FUNC) &_volesti_sample_points, 6},
    {"_volesti_sdp_approx", (DL_FUNC) &_volesti_sdp_approx, 4},
    {"_volesti_volume", (DL_FUNC) &_volesti_volume, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_volesti(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
