# Preprocessing tests (rounding, full-dimensional, inner ball, max ellipsoid)

add_executable(rounding_test rounding_test.cpp $<TARGET_OBJECTS:test_main>)
add_test(NAME test_round_min_ellipsoid COMMAND rounding_test -tc=round_min_ellipsoid)
add_test(NAME test_round_max_ellipsoid COMMAND rounding_test -tc=round_max_ellipsoid)
add_test(NAME test_round_svd COMMAND rounding_test -tc=round_svd)
add_test(NAME test_round_log_barrier_test COMMAND rounding_test -tc=round_log_barrier_test)
add_test(NAME round_max_ellipsoid_sparse COMMAND rounding_test -tc=round_max_ellipsoid_sparse)
add_test(NAME round_volumetric_barrier_test COMMAND rounding_test -tc=round_volumetric_barrier_test)
add_test(NAME round_vaidya_barrier_test COMMAND rounding_test -tc=round_vaidya_barrier_test)
add_test(NAME round_sparse_test COMMAND rounding_test -tc=round_sparse)
TARGET_LINK_LIBRARIES(rounding_test lp_solve ${MKL_LINK} coverage_config)

add_executable(full_dimensional_polytope_test full_dimensional_polytope_test.cpp $<TARGET_OBJECTS:test_main>)
add_test(NAME full_dimensional_polytope_canonical_simplex COMMAND full_dimensional_polytope_test -tc=full_dimensional_polytope_canonical_simplex)
add_test(NAME full_dimensional_polytope_simple_feasible COMMAND full_dimensional_polytope_test -tc=full_dimensional_polytope_simple_feasible)
add_test(NAME full_dimensional_polytope_line_segment COMMAND full_dimensional_polytope_test -tc=full_dimensional_polytope_line_segment)
add_test(NAME full_dimensional_polytope_high_dimensional COMMAND full_dimensional_polytope_test -tc=full_dimensional_polytope_high_dimensional)
add_test(NAME full_dimensional_polytope_multiple_constraints COMMAND full_dimensional_polytope_test -tc=full_dimensional_polytope_multiple_constraints)
add_test(NAME full_dimensional_polytope_hypercube_intersection COMMAND full_dimensional_polytope_test -tc=full_dimensional_polytope_hypercube_intersection)
add_test(NAME full_dimensional_polytope_sparse_constraint COMMAND full_dimensional_polytope_test -tc=full_dimensional_polytope_sparse_constraint)
add_test(NAME full_dimensional_polytope_orthogonality COMMAND full_dimensional_polytope_test -tc=full_dimensional_polytope_orthogonality)
add_test(NAME full_dimensional_polytope_infeasible COMMAND full_dimensional_polytope_test -tc=full_dimensional_polytope_infeasible)
TARGET_LINK_LIBRARIES(full_dimensional_polytope_test lp_solve ${SUITESPARSE_LIBRARIES} ${LAPACK_LIBRARIES} ${BLAS_LIBRARIES} ${MKL_LINK} coverage_config)

add_executable(test_internal_points test_internal_points.cpp $<TARGET_OBJECTS:test_main>)
add_test(NAME test_max_ball COMMAND test_internal_points -tc=test_max_ball)
add_test(NAME test_feasibility_point COMMAND test_internal_points -tc=test_feasibility_point)
add_test(NAME test_analytic_center COMMAND test_internal_points -tc=test_analytic_center)
add_test(NAME test_max_ball_sparse COMMAND test_internal_points -tc=test_max_ball_sparse)
add_test(NAME test_volumetric_center COMMAND test_internal_points -tc=test_volumetric_center)
add_test(NAME test_vaidya_center COMMAND test_internal_points -tc=test_vaidya_center)
TARGET_LINK_LIBRARIES(test_internal_points lp_solve ${MKL_LINK} coverage_config)

add_executable(max_ellipsoid_rounding_test max_ellipsoid_rounding_test.cpp $<TARGET_OBJECTS:test_main>)
add_test(NAME test_max_ellipsoid_rounding COMMAND max_ellipsoid_rounding_test)
TARGET_LINK_LIBRARIES(max_ellipsoid_rounding_test lp_solve ${MKL_LINK} coverage_config)

add_subdirectory(crhmc)
