function generateCodeFromMatlabResult = generateCodeFromMatlab(obj,userID,matFileByteStreamAsString)
%generateCodeFromMatlab(obj,userID,matFileByteStreamAsString)
%
%     Input:
%       userID = (string)
%       matFileByteStreamAsString = (string)
%   
%     Output:
%       generateCodeFromMatlabResult = (string)

% Build up the argument lists.
values = { ...
   userID, ...
   matFileByteStreamAsString, ...
   };
names = { ...
   'userID', ...
   'matFileByteStreamAsString', ...
   };
types = { ...
   '{http://www.w3.org/2001/XMLSchema}string', ...
   '{http://www.w3.org/2001/XMLSchema}string', ...
   };

% Create the message, make the call, and convert the response into a variable.
soapMessage = createSoapMessage( ...
    'http://forces.ethz.ch', ...
    'generateCodeFromMatlab', ...
    values,names,types,'document');
response = callSoapService( ...
    obj.endpoint, ...
    'http://forces.ethz.ch/generateCodeFromMatlab', ...
    soapMessage);
generateCodeFromMatlabResult = parseSoapResponse(response);
