##############################################################################
# GitHub Actions Workflow for volesti to build tests with GCC
#
# Copyright (c) 2020-2022 Vissarion Fisikopoulos
#
# Licensed under GNU LGPL.3, see LICENCE file
##############################################################################
name: cmake-examples

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.config.os }} - ${{ matrix.config.compiler }}
    strategy:
          fail-fast: false
          matrix:
            config:
              - {os: ubuntu-22.04, compiler_pkg: clang-11, compiler: clang++-11}
              - {os: ubuntu-22.04, compiler_pkg: g++-11, compiler: g++-11}
    runs-on: ${{ matrix.config.os }}
    steps:
      - uses: actions/checkout@v1
      - run: sudo apt-get update || true;
             sudo apt-get install ${{ matrix.config.compiler_pkg }} lp-solve libomp-dev libopenblas-dev libarpack2-dev;
      - name: Build examples
        run: |
          cd examples
          for dir in */; do
            if [ "$dir" != "EnvelopeProblemSOS/" ] && [ "$dir" != "python_utilities/" ]; then
              echo
              echo "Building examples in $dir ....................."
              cd "$dir"
              mkdir build && cd build
              cmake -DCMAKE_CXX_COMPILER=${{ matrix.config.compiler }} -DUSE_MKL=OFF ..
              make
              cd ../..
            fi
          done

