name: CI-macOS-AppleClang

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.config.os }} - ${{ matrix.config.compiler }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macos-12, compiler: clang++}
          - {os: macos-12, compiler: clang++-13}
          - {os: macos-12, compiler: clang++-14}
          - {os: macos-13, compiler: clang++}
          - {os: macos-13, compiler: clang++-15}
          - {os: macos-14, compiler: clang++}
          - {os: macos-14, compiler: clang++-16}
          - {os: macos-14, compiler: clang++-17}

    runs-on: ${{ matrix.config.os }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Verify System & Compiler
        run: |
          echo "System Info:"
          uname -a
          echo "Using Clang version:"
          ${{ matrix.config.compiler }} --version

      - name: Build and Test
        run: |
          rm -rf build
          mkdir build
          cd build
          
          if [[ "$(uname -s)" == "Darwin" ]]; then
            CXX_FLAGS="-fsanitize=undefined -g"   # No memory sanitizer on macOS
          else
            CXX_FLAGS="-fsanitize=memory -fsanitize=undefined -g"
          fi
          
          cmake -D CMAKE_CXX_COMPILER=${{ matrix.config.compiler }} \
                -D CMAKE_CXX_FLAGS="${CXX_FLAGS}" \
                -D DISABLE_NLP_ORACLES=ON \
                -D USE_MKL=OFF \
                ../test
          make
          ctest --verbose

