# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

poly_gen <- function(kind_gen, Vpoly_gen, dim_gen, m_gen) {
    .Call('_volesti_poly_gen', PACKAGE = 'volesti', kind_gen, Vpoly_gen, dim_gen, m_gen)
}

rounding <- function(A, walk_len, coord, ball_walk, delta, Vpoly, Zono) {
    .Call('_volesti_rounding', PACKAGE = 'volesti', A, walk_len, coord, ball_walk, delta, Vpoly, Zono)
}

get_ball_ann <- function(P, e, lb_ratio = 0.1, ub_ratio = 0.2) {
    .Call('_volesti_get_ball_ann', PACKAGE = 'volesti', P, e, lb_ratio, ub_ratio)
}

